version: '2'
services:
  etcd:
    image: quay.io/coreos/etcd:v2.3.1
    command: >
      -advertise-client-urls http://etcd:2379
      -listen-client-urls http://0.0.0.0:2379
  test:
    build: .
    links:
      - etcd
    depends_on:
      - etcd
  traefik:
    ports:
      - "8080:8080"
      - "80:80"
    image: traefik:v1.0.3
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
    links:
      - test
      - etcd
    depends_on:
      - test
      - etcd
